# Generated by Django 2.2 on 2020-10-26 08:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongtermMissionList',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('assign_time', models.DateTimeField(default=datetime.date(2020, 10, 26))),
                ('launch_time', models.DateTimeField(default=datetime.date(2020, 10, 26))),
                ('expected_finish_time', models.DateField()),
                ('emergency_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('important_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('detail', models.TextField(blank=True, max_length=500)),
                ('releated_link_1', models.URLField(blank=True)),
                ('releated_link_2', models.URLField(blank=True)),
                ('releated_link_3', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortermMissionList',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('assign_time', models.DateTimeField(default=datetime.date(2020, 10, 26))),
                ('launch_time', models.DateTimeField(default=datetime.date(2020, 10, 26))),
                ('expected_finish_time', models.DateField()),
                ('emergency_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('important_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('detail', models.TextField(blank=True, max_length=500)),
                ('related_link_1', models.URLField(blank=True)),
                ('related_link_2', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='slogan',
            fields=[
                ('text', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=datetime.date(2020, 10, 26))),
            ],
        ),
    ]
