# Generated by Django 2.2 on 2020-10-27 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissionCreate', '0002_auto_20201026_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermmissionlist',
            name='assign_time',
            field=models.DateTimeField(default=datetime.date(2020, 10, 27)),
        ),
        migrations.AlterField(
            model_name='longtermmissionlist',
            name='launch_time',
            field=models.DateTimeField(default=datetime.date(2020, 10, 27)),
        ),
        migrations.AlterField(
            model_name='shortermmissionlist',
            name='assign_time',
            field=models.DateTimeField(default=datetime.date(2020, 10, 27)),
        ),
        migrations.AlterField(
            model_name='shortermmissionlist',
            name='launch_time',
            field=models.DateTimeField(default=datetime.date(2020, 10, 27)),
        ),
        migrations.AlterField(
            model_name='slogan',
            name='create_time',
            field=models.DateTimeField(default=datetime.date(2020, 10, 27)),
        ),
    ]
